services:
  postgres:
    image: postgres:16
    container_name: team4db
    environment:
      POSTGRES_USER: team4
      POSTGRES_PASSWORD: team4pass
      POSTGRES_DB: team4db
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: team4_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: team4@ugm.com
      PGADMIN_DEFAULT_PASSWORD: team4pass
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmindata:/var/lib/pgadmin
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: tim4_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrantdata:/qdrant/storage

  redis:
    image: redis:7-alpine
    container_name: tim4_redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tim4_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - qdrant
      - redis
    command: >
      uvicorn backend.app.main:app --host 0.0.0.0 --port 8000

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tim4_worker
    env_file:
      - .env
    depends_on:
      - postgres
      - qdrant
      - redis
    command: >
      celery -A backend.app.celery_app.celery worker --loglevel=INFO

volumes:
  pgdata:
  pgadmindata:
  qdrantdata: