"""Initial migration

Revision ID: 232297cd4d32
Revises: 
Create Date: 2026-03-11 03:38:49.623059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '232297cd4d32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_manifest',
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('batch_type', sa.Enum('model1_batch', 'gtrends', 'qdrant_sync', 'crawl_run', name='batch_type_enum'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('auto_labeled', sa.Integer(), nullable=True),
    sa.Column('manual_queue', sa.SmallInteger(), nullable=True),
    sa.Column('sft_total', sa.Integer(), nullable=True),
    sa.Column('qdrant_synced', sa.Integer(), nullable=True),
    sa.Column('success_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('records_error', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'RUNNING', 'FAILED', name='batch_status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('crawler_config',
    sa.Column('crawler_id', sa.String(length=64), nullable=False),
    sa.Column('crawler_name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'instagram', 'youtube_shorts', 'media_online', 'google_trends', name='platform_enum'), nullable=False),
    sa.Column('max_results_per_keyword', sa.Integer(), nullable=True),
    sa.Column('max_comments_per_post', sa.SmallInteger(), nullable=True),
    sa.Column('min_comment_likes', sa.Integer(), nullable=True),
    sa.Column('request_delay_sec', sa.Integer(), nullable=True),
    sa.Column('daily_target', sa.Integer(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('crawler_id'),
    sa.UniqueConstraint('platform')
    )
    op.create_table('keyword_corpus',
    sa.Column('keyword_id', sa.String(length=64), nullable=False),
    sa.Column('keyword_text', sa.String(length=500), nullable=False),
    sa.Column('source', sa.Enum('trends24', 'google_trends', 'kpm_internal', name='keyword_source_enum'), nullable=False),
    sa.Column('taxonomy_category', sa.Enum('Integritas & Penegakan Hukum', 'Kebijakan & Layanan Publik', 'Kinerja Pemerintah', 'Keamanan Siber & Ketertiban Digital', 'Kesejahteraan & Bantuan Sosial', 'Infrastruktur & Layanan Transportasi', 'Ekonomi Digital', 'Ketenagakerjaan', 'Layanan Kesehatan', 'Pendidikan dan Pengembangan SDM', 'Krisis Sosial & Kebencanaan', name='taxonomy_category_enum'), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('volume_estimate', sa.Integer(), nullable=True),
    sa.Column('volume_source', sa.Enum('keyword_planner', 'pytrends_estimate', 'trends24_tweets', name='volume_source_enum'), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('can_auto_deactivate', sa.Boolean(), nullable=True),
    sa.Column('crawl_priority', sa.Enum('tinggi', 'sedang', 'rendah', name='crawl_priority_enum'), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by', sa.String(length=100), nullable=True),
    sa.Column('crawl_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    op.create_index(op.f('ix_keyword_corpus_is_active'), 'keyword_corpus', ['is_active'], unique=False)
    op.create_table('taxonomy_category',
    sa.Column('category_id', sa.String(length=16), nullable=False),
    sa.Column('category_name', sa.Enum('Integritas & Penegakan Hukum', 'Kebijakan & Layanan Publik', 'Kinerja Pemerintah', 'Keamanan Siber & Ketertiban Digital', 'Kesejahteraan & Bantuan Sosial', 'Infrastruktur & Layanan Transportasi', 'Ekonomi Digital', 'Ketenagakerjaan', 'Layanan Kesehatan', 'Pendidikan dan Pengembangan SDM', 'Krisis Sosial & Kebencanaan', name='taxonomy_category_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('keyword_status_log',
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('keyword_id', sa.String(length=64), nullable=False),
    sa.Column('old_status', sa.Boolean(), nullable=False),
    sa.Column('new_status', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Enum('auto_threshold', 'manual_override', 'new_keyword', name='log_reason_enum'), nullable=False),
    sa.Column('trend_score_at_change', sa.Float(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword_corpus.keyword_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_keyword_status_log_keyword_id'), 'keyword_status_log', ['keyword_id'], unique=False)
    op.create_table('keyword_trend_history',
    sa.Column('history_id', sa.String(length=64), nullable=False),
    sa.Column('keyword_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interest_score', sa.Integer(), nullable=True),
    sa.Column('region_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword_corpus.keyword_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_keyword_trend_history_keyword_id'), 'keyword_trend_history', ['keyword_id'], unique=False)
    op.create_table('labeled_content',
    sa.Column('label_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.Enum('post', 'comment', name='source_type_enum'), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('label_type', sa.Enum('auto', 'manual', name='label_type_enum'), nullable=False),
    sa.Column('taxonomy_category', sa.Enum('Integritas & Penegakan Hukum', 'Kebijakan & Layanan Publik', 'Kinerja Pemerintah', 'Keamanan Siber & Ketertiban Digital', 'Kesejahteraan & Bantuan Sosial', 'Infrastruktur & Layanan Transportasi', 'Ekonomi Digital', 'Ketenagakerjaan', 'Layanan Kesehatan', 'Pendidikan dan Pengembangan SDM', 'Krisis Sosial & Kebencanaan', name='taxonomy_category_enum'), nullable=True),
    sa.Column('sentiment', sa.Enum('positif', 'negatif', 'netral', name='sentiment_enum'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('labeled_by', sa.String(length=100), nullable=True),
    sa.Column('labeled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_manifest.batch_id'], ),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_index(op.f('ix_labeled_content_batch_id'), 'labeled_content', ['batch_id'], unique=False)
    op.create_index(op.f('ix_labeled_content_source_id'), 'labeled_content', ['source_id'], unique=False)
    op.create_table('raw_content',
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'instagram', 'youtube_shorts', 'media_online', 'google_trends', name='platform_enum'), nullable=False),
    sa.Column('content_type', sa.Enum('post', 'video', 'article', 'carousel', 'trend', name='content_type_enum'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('url_source', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.Column('keyword_refs', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('taxonomy_category', sa.Enum('Integritas & Penegakan Hukum', 'Kebijakan & Layanan Publik', 'Kinerja Pemerintah', 'Keamanan Siber & Ketertiban Digital', 'Kesejahteraan & Bantuan Sosial', 'Infrastruktur & Layanan Transportasi', 'Ekonomi Digital', 'Ketenagakerjaan', 'Layanan Kesehatan', 'Pendidikan dan Pengembangan SDM', 'Krisis Sosial & Kebencanaan', name='taxonomy_category_enum'), nullable=True),
    sa.Column('taxonomy_confidence', sa.Float(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('crawl_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_manifest.batch_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_raw_content_batch_id'), 'raw_content', ['batch_id'], unique=False)
    op.create_index(op.f('ix_raw_content_platform'), 'raw_content', ['platform'], unique=False)
    op.create_table('audio_manifest',
    sa.Column('audio_id', sa.String(length=64), nullable=False),
    sa.Column('content_id_ref', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('file_format', sa.Enum('mp3', 'mp4', 'wav', name='audio_format_enum'), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('is_original_sound', sa.Boolean(), nullable=True),
    sa.Column('has_speech', sa.Boolean(), nullable=True),
    sa.Column('passed_tech_filter', sa.Boolean(), nullable=True),
    sa.Column('is_informative', sa.Boolean(), nullable=True),
    sa.Column('transcript_result', sa.Text(), nullable=True),
    sa.Column('crawl_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id_ref'], ['raw_content.content_id'], ),
    sa.PrimaryKeyConstraint('audio_id')
    )
    op.create_index(op.f('ix_audio_manifest_content_id_ref'), 'audio_manifest', ['content_id_ref'], unique=False)
    op.create_table('image_manifest',
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('content_id_ref', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('file_format', sa.Enum('jpg', 'png', 'webp', name='image_format_enum'), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('file_size_kb', sa.Float(), nullable=True),
    sa.Column('passed_tech_filter', sa.Boolean(), nullable=True),
    sa.Column('is_informative', sa.Boolean(), nullable=True),
    sa.Column('caption_result', sa.Text(), nullable=True),
    sa.Column('crawl_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id_ref'], ['raw_content.content_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_image_manifest_content_id_ref'), 'image_manifest', ['content_id_ref'], unique=False)
    op.create_table('post_comment',
    sa.Column('comment_id', sa.String(length=64), nullable=False),
    sa.Column('post_content_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'instagram', 'youtube_shorts', 'media_online', 'google_trends', name='platform_enum'), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('is_reply', sa.Boolean(), nullable=True),
    sa.Column('parent_comment_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawl_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_manifest.batch_id'], ),
    sa.ForeignKeyConstraint(['post_content_id'], ['raw_content.content_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_post_comment_batch_id'), 'post_comment', ['batch_id'], unique=False)
    op.create_index(op.f('ix_post_comment_post_content_id'), 'post_comment', ['post_content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_comment_post_content_id'), table_name='post_comment')
    op.drop_index(op.f('ix_post_comment_batch_id'), table_name='post_comment')
    op.drop_table('post_comment')
    op.drop_index(op.f('ix_image_manifest_content_id_ref'), table_name='image_manifest')
    op.drop_table('image_manifest')
    op.drop_index(op.f('ix_audio_manifest_content_id_ref'), table_name='audio_manifest')
    op.drop_table('audio_manifest')
    op.drop_index(op.f('ix_raw_content_platform'), table_name='raw_content')
    op.drop_index(op.f('ix_raw_content_batch_id'), table_name='raw_content')
    op.drop_table('raw_content')
    op.drop_index(op.f('ix_labeled_content_source_id'), table_name='labeled_content')
    op.drop_index(op.f('ix_labeled_content_batch_id'), table_name='labeled_content')
    op.drop_table('labeled_content')
    op.drop_index(op.f('ix_keyword_trend_history_keyword_id'), table_name='keyword_trend_history')
    op.drop_table('keyword_trend_history')
    op.drop_index(op.f('ix_keyword_status_log_keyword_id'), table_name='keyword_status_log')
    op.drop_table('keyword_status_log')
    op.drop_table('taxonomy_category')
    op.drop_index(op.f('ix_keyword_corpus_is_active'), table_name='keyword_corpus')
    op.drop_table('keyword_corpus')
    op.drop_table('crawler_config')
    op.drop_table('batch_manifest')
    # ### end Alembic commands ###
